import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-source-code-pro",
})

export const metadata: Metadata = {
  title: "Web portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceCodePro.variable} bg-black text-white min-h-screen flex flex-col`}>
        <NavBar />
        <main className="pt-32 px-4 flex-grow">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
